version: '3'

services:
  strapi:
    build: .
    image: my-strapi-app
    container_name: strapi
    restart: unless-stopped
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: 'false'
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    depends_on:
      - postgres
    networks:
      - strapi

  postgres:
    image: arm64v8/postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5434:5432'
    volumes:
      - strapi-data:/var/lib/postgresql/data
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
